# Source: mongodb/templates/standalone/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-item-stock
  namespace: default
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.30.6
    app.kubernetes.io/instance: mongodb-item-stock
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mongodb
    env: staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
