# Source: keycloak/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: default
  labels:
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-5.2.3
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: keycloak
    env: staging
type: 'ENC[AES256_GCM,data:NXa1jMOd,iv:Q3YrpnV5m/8R4jpC8Q6xHsh2KKDEvylkBYnZSU9bWZw=,tag:0hIJGn1m7Vg8fwPy3np1qQ==,type:str]'
data:
  admin-password: 'ENC[AES256_GCM,data:8liJ+ivsqdDsBfPr,iv:Os9A/gvma5XjHymrX6yXo2oOcxOfnTpjzNGIroAh938=,tag:Q2UDl3G6M1T8SvNCUBJP6Q==,type:str]'
  management-password: 'ENC[AES256_GCM,data:m16rsgKrxxLTX92H2k5XPw==,iv:MQEFOJdyjIZd2vhxMRWcJKeECMxfT/dtFp7aIaga6DQ=,tag:1RN7GijpLAFyWSDTqMUJSg==,type:str]'
  user-password: 'ENC[AES256_GCM,data:pFdtHmWwvMR2DTBd,iv:JlV1GdZC0q4zoNXsS+uWgBnQRtox8TRqO/7KCdpJBBU=,tag:J0EtLFyDFUN2cKaB9MMWPQ==,type:str]'
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2022-01-30T18:57:50Z'
  mac: 'ENC[AES256_GCM,data:QyIFUomhGO13U1bmjTdmH5MQVqvVTeIasPF91Ncl4Z3pKLkt51MGGdSKSGkGdZIHPMD2lplDrNTenp6PPGYDtthcF6Bk/0o7JB5xRsn5CMCAoZP90TrEAkAJGM74GUoTlfi1qPv9PRnChRHXwAj9lFljCVtf/QzWpl0mRPtw360=,iv:BdQuUL8u+cTxQFlfEY2l00H2UzAp+psODSkdCIUp0w0=,tag:QzOLlD+w3NzHUJX5MEc7xw==,type:str]'
  pgp:
  - created_at: '2022-01-30T18:57:50Z'
    enc: |
      -----BEGIN PGP MESSAGE-----

      hQIMA0v3SRnpVg8+AQ//YrR/zcO6FpGcaUcvmube6VCvEdY8pf/0dAM3lwHto00V
      2MPnqEceBUHVwFuehxdjK+AuEKsJb97mpe4cibynfLwuUjMIr0d6xsO+D7FTXN5G
      1GcA/x0GTuDAp13i8O1O3hPbWCQ6bljtextCkYHMXE7foEYgIzrQby0bzlhVVIP4
      /l1BLxBwQuWKQN91/VL8YsmlJyudYzqfK2TEQeJ5z6erWLclZhzW46foXe1GIPFt
      VLdX9pOWoZpChyeeoz0hpDuCuMP/LD/vFBwUUnbb9i1i0xuJP6WN9paBW1QCzD90
      0lFwuJKIDhcoPrOOFdzsoHEL5nYeODwYK6mJAT+sIhioxIJUJIVLLzspc9cECbjY
      n3rj1Py9Gg63TdSQWPiBRcMs35irWiICvOMoBMPow8sbVf9uTQUwABIsarEOwkt9
      GJKNwS1pMEuAjFKNzLhSdxW5htwX+vOvLVpBg/T1coSuMvZWtDkNRjQ96gTbejho
      2wdqMYq7Ci6P94T8fSRRu8ywwwgCywmi6JLl7HepUhncSN9lMRrCJH/FgyKPt4jE
      SZU9Ilx9RRiNlkf60j+Y2AhKIBDf8uOOXb+VJqkDUd9uiP4yrG+gY++4tJT3fPIQ
      rDmJaOvZapmr4+BOTboM3pw9ikDwJjgpTRTARQSkZ9xojWxZvamtRTohQHAqXcXS
      XgHjnfu3+rMUfda2h0b3RoR7w7AEB/8FptDydQaZ5InXOr/VeVxy6ETrRDj3aAC2
      14cSvJ0gAhGhCaqrQ0KuX6oYaGlxk5XllOQyzs0XSBOwU6AqvAOXh3G3OOMxe48=
      =DZ2l
      -----END PGP MESSAGE-----
    fp: FFA6D9C42D878F5C
  unencrypted_regex: ^(kind|apiVersion|group|metadata)$
  version: 3.7.1
