# Source: mongodb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-item-stock
  namespace: default
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.30.6
    app.kubernetes.io/instance: mongodb-item-stock
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/version: v0.0.1
    env: staging
type: 'ENC[AES256_GCM,data:mV9Lj99o,iv:5j3geNup80rO/6An/g5J+FGBFS5QP1UGulOhZHxZiQ4=,tag:nm1wHOxYEPkuEyu4OXOqLw==,type:str]'
data:
  mongodb-root-password: 'ENC[AES256_GCM,data:hLBVZTTBSn45686f,iv:9h0ZBEClStWTXJB4cDYWZSsyjJs9L2HTmDcZEH8t+L4=,tag:1PTmPuQqlB2P2aR4/pEa/g==,type:str]'
  mongodb-passwords: 'ENC[AES256_GCM,data:polRflsewuXg8rqn,iv:yugN3Sl+BRdkkrS872hAvcd/Lkt91RjUO4oUuPiwVHw=,tag:4wRrUewikbMvjd7SdM/dVw==,type:str]'
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2022-01-10T19:08:24Z'
  mac: 'ENC[AES256_GCM,data:UeVs84SkKCYu7gtqJneDNN6XRU6WjdZXVSqIsBrjBuOXoemkECst/kGn6iMfg2ekdO0cEVgRQ0tXbnvFI7pXKdwIBxpDPp4cgU6KrlJ38rptmiR+E77w3KRfGKsMvz3rblzkxr8K5qVdREenaoOCJInCQ8a8Fj+O5H1Aw6BysW0=,iv:mDPzwBpyLYgHGyQY+V3RvUuQfaw3pzHKO3zXzeUvHoY=,tag:/cHvHpePA7o1yBPejHSopA==,type:str]'
  pgp:
  - created_at: '2022-01-10T19:08:24Z'
    enc: |
      -----BEGIN PGP MESSAGE-----

      hQIMA0v3SRnpVg8+AQ//Wq/X1wgqUt/1bbgVKibjYHj6w19vsBcE6qwiWPprYfCy
      Ulno6RmXSMsEfzmFfOqpzB9uXPcUJ+f9qADFmcytnaM9odqVG2tcccDK0VMArwVa
      1KGL7tKCOMYtvafUXPxd+52x/JfmxKaYZ3YkvDwq05BmFWzW2EWCGDJXiIyuRvTg
      K57Y8XP/eb3vO5ZEwqddgjOnZz5/9tofJnlpGIwpEbkzCMIZ5KZ3SAXNkI3xOaVD
      Kx2pIs8EDN1J3vca+uOqdyax7zRFP3QYAlFe7PNq2a2QBMZbEwcRi+sh54907wUf
      yPQDI8sY1IHVJRByDHXFqghfA/jgL7nreuEJeIEI48JZ+bUJIgJvkzob2nGs4c0a
      D6kf/8M+41CgLocicNbx1azLTzuxMRO6MzywMhxf5sFiKznHxuuWNm45cHoXw9g7
      UlxIuFrWYYEK1t9oNe9uV8s+1nNW+UZ/nTJD/lUyiqBRVeeQPw5tu0v6PtNL1aXX
      Mh/zF+04ciAUDoMOq4C+nmsFzN+r8RJE0no8KClhvPRGSr+ZuoJXIBcyroKUHBHh
      e6ddsdNxLWh1tzSF14ZL7L9j3ILlhlmCsEVosP+8Zgk+ov2J/Ky0iiOgNUziHHEX
      NBJYI0o61Rds4KdhDjSA/HF0jkYKLvUedzEuo2WHQQxmSzGeAECmpt0OczK/kH7S
      XgEfHG4GqgYgmWSoFf3jah3pQGmShFC1XuMS8bWmZY20Ls203bMVDjQc7cczWjor
      /YWwweOSi84VxEvw26VBkNOerUgRLlSByg56aEF/Auh1+q8wMlXWBguCtNz63kU=
      =2LfC
      -----END PGP MESSAGE-----
    fp: FFA6D9C42D878F5C
  unencrypted_regex: ^(kind|apiVersion|group|metadata)$
  version: 3.7.1
