# Source: mongodb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-item-stock
  namespace: default
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.30.6
    app.kubernetes.io/instance: mongodb-item-stock
    app.kubernetes.io/managed-by: Helm
    env: staging
secrets:
  - name: mongodb-item-stock
