# Source: rabbitmq/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: default
  labels:
    app.kubernetes.io/name: rabbitmq
    helm.sh/chart: rabbitmq-8.24.10
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: v0.0.1
    env: staging
type: 'ENC[AES256_GCM,data:0ydmiNmq,iv:ItTxGq7xgIo0F/T7NN89omyiiR9VobzrX04thhoQgns=,tag:Bxs6LrwDUYQ1AMyURYFIJQ==,type:str]'
data:
  rabbitmq-password: 'ENC[AES256_GCM,data:aRdhz8V93ORZxdYk,iv:gmA2sCtL6FvSgeA/uXueFsnqmEI+B5IJ6C7JSExzxBQ=,tag:Lpc1QtLitL6jGqw1X7EGVw==,type:str]'
  rabbitmq-erlang-cookie: 'ENC[AES256_GCM,data:tsbdoBQsXA5tAauGxtg7fjepXZzAS/cjRes66+vllnDqgMBeUDeRScBrrMU=,iv:AJ/G+/M/stXNmBQfgs3QrXxRSCaY2ZHXuVZEk3bMWIA=,tag:evuctRlyxEUQ1mMsFRntmQ==,type:str]'
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2022-01-22T18:12:38Z'
  mac: 'ENC[AES256_GCM,data:3SoDxJlMlaVXBFX5ZRe/0XVY9iVsytOWFhLPzEZHVImIzWI0eu4SErGHS8eZmgT8v9T8Fw7jSv/e338AgAWRXB06wXDfSTX244Jiga1OFDp8Nm02XtMW/fVyk31FZgfYoIMYZc60uAg0LKdRfWjOO+2AIw3j+9L9YRKRHVaHPV0=,iv:M0Q0WyhiNahytUWhCV0vPBEppt4Uk7ky0/4tObQgg2k=,tag:EYWGfYWhErXzRFaBSL8tGQ==,type:str]'
  pgp:
  - created_at: '2022-01-22T18:12:38Z'
    enc: |
      -----BEGIN PGP MESSAGE-----

      hQIMA0v3SRnpVg8+ARAAjdrC5O00sKdxwi01QKvUm8QgDiy+30EDBOn1QXsrbO44
      BZG8Z8Iqe+PAnCtjW1ElZMOQn88WLUAOdUzZca75EK1FFCqO33r25+j7hN8LCSh1
      KWbW+JQ84piWo7i9WEAnv4SCggzkvBXTol0f00pur/Zj2lVCqmWlo2I7G6l3bbmZ
      QaZ6I1OzkSNgMaqlFV8BbXgy2QmnLy2Jr2VWvM8YgYN1nA68eAPP7IDLGEu9Nwyc
      j1eIBkmR3XDdax+n/iQwshoq3TcrNuiwb6eRE51etOPjw620qJS6kgiR5b3E8fAj
      lKYRGZW8+H7dHBDMvqPcoyr82bK51sErcmL2tA6FuWFM4vfk1mnNUmuUyGfVjAUg
      dTjlwKXyKj3/a1zchCgVZ4B/FV3M1vh6y5ns2jO3S4GE17vmdtpQwKadvKW3Ls6N
      6q5ZD7hrRkYazDjF2VuutWNszLmGXV1nIW2XHDpWXHTD1vDB3egmIP6Tb2hYKUkH
      d9I5Obp9f3/BROA2iwWPcUBQPbq/F5gxmsrLaVW7WneChWJv0V6V9s8LJOXSTz91
      tkUyZJv0LOQ+DV0ndom+t5/4SGfc38P+NUWLDAJwcNyBrlujlCxiKaonuz78+F43
      Os2nTB7TOaHhyVA8OoWS4h05nQ4OBm3Oh2umA6lLIIt0j+GiQUPwA0gOHXE+JabS
      XAGWHFELrtW1YpQF9KkEDwGv/JKQVbJj7X1fuT7sktq6lNkeYn1ikhzikPQjK6tH
      aM5d6uCle9nZYsSh1ZP9YRw9vDQdZIeCqAXAVfzxoXm2nW5ZKx/skOPEpdgA
      =wznu
      -----END PGP MESSAGE-----
    fp: FFA6D9C42D878F5C
  unencrypted_regex: ^(kind|apiVersion|group|metadata)$
  version: 3.7.1
