# Source: rabbitmq/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: default
  labels:
    app.kubernetes.io/name: rabbitmq
    helm.sh/chart: rabbitmq-8.24.10
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/managed-by: Helm
    env: staging
type: 'ENC[AES256_GCM,data:ZzOa32FE,iv:d1bp6l645+ieuoiWD2P+HXpAE4656a94QJkpYwhnirc=,tag:EGQrNOhiDo9ed+NyVAxr8w==,type:str]'
data:
  rabbitmq-password: 'ENC[AES256_GCM,data:BBqAsd6znvgWOnhs,iv:ezmIF30Kx2jWRg3jXkAFagcbDRmsuQEI278iguhaK6Q=,tag:WPQFyVaSbHWcPByWSN1hhQ==,type:str]'
  rabbitmq-erlang-cookie: 'ENC[AES256_GCM,data:mLvBiL5XokARCHoBm2Ku+3ksBf16Hozj5ubOfZa0f9RhypknK/2X/ZBWv+8=,iv:thVIeBg42fRwv4cr5Bo8ln8Rz/gBEjTcziqC9brqnZA=,tag:vosOjLGAhrkqM3rVAcVOlA==,type:str]'
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2022-01-30T18:57:50Z'
  mac: 'ENC[AES256_GCM,data:DAoPBSV1nT7SkBL2JzPbTwcRzrQRzux7vcu9UcZObZRFujhMK+4L45aEB2KUclBz7d+AHnzIrAihtl2hxaxzQKrUgRbGoLB6w60cHC9YnGFdQZ0sMljNxmC51QDCZEc3r4CEfAFFnI5kncLl3VVEdvTwIJVl9C6SoANM4D59Rig=,iv:nb1JmLvI52HzLfXQUn9UsybpcTZ5Bd9EvHdg04FVKFk=,tag:xCOOdrFyK8v2R0boKEdgaw==,type:str]'
  pgp:
  - created_at: '2022-01-30T18:57:50Z'
    enc: |
      -----BEGIN PGP MESSAGE-----

      hQIMA0v3SRnpVg8+ARAAjdR99OrtX777pON4H73hTHCZ5u2X53yR8MjkiC8/Aa1p
      7zP5VytNnKo1dMEzfEAYJp2g4M06zqEcH6YkHZ/OZW6nP+wLDkuqyUp0k1U9lluH
      qadrFr5vB2l50tktigHFHAByF6a73VON8gQfKiKwsxVKcROxIdRB2kUKQGh3IaOb
      G/YXzFsV/QcL7TgnOiIXrZ6TZ6tTEoMOXiU/QOv+LQVk8U2zf+SnfjHLPmXEqmhQ
      ii47WVFhlrLKdjIdagrl9/MAHNxWmNeTupQTUJ1qO4Bv69isMq5yr8aQvmv0HoX5
      bK/sf14gJoFuX2SKEdcDTNIQ05jyk0pMMtW6dVEZhUUcrfkCwfH5HE52LL9wSaT3
      WvUQw7XP6UlE009uTiJiorEVOLpOyJMmYoZ3Ecf1ugYOEPv/LduAMqP6qugI47hL
      7Y52QrRXBoRAGSinG7KZ0cKf69n4s29QxOLvImpFU7ND41uPpLKQNzRxKvIXZZqc
      QpfTeFQ+OyZw20DeTqE+Vnc8g6AhQsIhPuK7HKHwro0w14w5uFvgm3kxmQWiXyy/
      KmB6DjDmM7I7tr4pxzzBLFF9DLwnDW4hp9zhVWm6kGsp7sw+mfEQ+t7r0ryt3C02
      lFxNtSRqoHooc4erMNzkznxLMiGtKPW215hbXA9ojhEsT22s2l//UQkibLgevdjS
      XgGn0cNMS9clKSAnp01Q4AqKXyUWPKglmHhhABuMjvy6Q3YOL3Zt50bOgynw2bj+
      //D1ABHRB4z0RTg6I1ZPa28gbY3a+vdrZiKoMNeJFCSu2Jq9Xkin9Q6HtBoFqBY=
      =uAuD
      -----END PGP MESSAGE-----
    fp: FFA6D9C42D878F5C
  unencrypted_regex: ^(kind|apiVersion|group|metadata)$
  version: 3.7.1
