# Source: rabbitmq/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq
  namespace: default
  labels:
    app.kubernetes.io/name: rabbitmq
    helm.sh/chart: rabbitmq-8.24.10
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/managed-by: Helm
    env: staging
automountServiceAccountToken: true
secrets:
  - name: rabbitmq
