# Source: elasticsearch/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-master
  labels:
    heritage: Helm
    release: elasticsearch
    chart: elasticsearch
    app: elasticsearch-master
    env: staging
spec:
  type: ClusterIP
  selector:
    release: elasticsearch
    chart: elasticsearch
    app: elasticsearch-master
    env: staging
  ports:
  - name: http
    protocol: TCP
    port: 9200
  - name: transport
    protocol: TCP
    port: 9300
---
# Source: elasticsearch/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-master-headless
  labels:
    heritage: Helm
    release: elasticsearch
    chart: elasticsearch
    app: elasticsearch-master
    env: staging
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
spec:
  clusterIP: None # This is needed for statefulset hostnames like elasticsearch-0 to resolve
  # Create endpoints also if the related pod isn't ready
  publishNotReadyAddresses: true
  selector:
    app: elasticsearch-master
    env: staging
  ports:
  - name: http
    port: 9200
  - name: transport
    port: 9300
