apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-api
  annotations:
    konghq.com/plugins: 'app-cors-plugin, app-jwt-plugin'
    konghq.com/strip-path: 'true'
  labels:
    env: staging
spec:
  ingressClassName: kong
  tls:
    - hosts:
        - api.latihan.jocki.me # kpt-set: api.${domain}
      secretName: tls-secret
  rules:
    - host: api.latihan.jocki.me # kpt-set: api.${domain}
      http:
        paths:
          - path: /stock-item-service
            pathType: Prefix
            backend:
              service:
                name: stock-item-service
                port:
                  number: 8080
          - path: /search
            pathType: Prefix
            backend:
              service:
                name: elasticsearch-master
                port:
                  number: 9200
