apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-web
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  labels:
    app.kubernetes.io/version: v0.0.1
    env: staging
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - web.latihan.jocki.me
      secretName: tls-secret
  rules:
    - host: web.latihan.jocki.me
      http:
        paths:
          - pathType: Prefix
            path: /(.*)
            backend:
              service:
                name: angular-web
                port:
                  number: 80
