apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-item-service
  labels:
    app.kubernetes.io/name: stock-item-service
    app.kubernetes.io/component: app-server
    app.kubernetes.io/part-of: stock-item-service
    env: staging
  annotations:
    config.kubernetes.io/depends-on: 'apps/namespaces/default/StatefulSet/mongodb-item-stock, apps/namespaces/default/StatefulSet/keycloak, apps/namespaces/default/StatefulSet/rabbitmq, apps/namespaces/default/StatefulSet/kong'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: stock-item-service
      env: staging
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stock-item-service
        app.kubernetes.io/component: app-server
        app.kubernetes.io/part-of: stock-item-service
        env: staging
    spec:
      containers:
        - name: stock-item-service
          image: 'ghcr.io/jockihendry/latihan-k8s-stock-item-service:sha-76cfad6' # kpt-set: ghcr.io/jockihendry/latihan-k8s-stock-item-service:${stock_item_service_version}
          env:
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: 'http://keycloak/auth/realms/latihan'
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: 'https://auth-default.latihan.jocki.me/auth/realms/latihan' # kpt-set: https://auth-${tenant}.${domain}/auth/realms/latihan
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: stock-item-service
  labels:
    app.kubernetes.io/name: stock-item-service
    app.kubernetes.io/component: app-server
    app.kubernetes.io/part-of: stock-item-service
    env: staging
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: stock-item-service
    env: staging
  ports:
    - name: http
      port: 8080
