apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-web
  labels:
    app.kubernetes.io/name: angular-web
    app.kubernetes.io/version: 0.0.1
    app.kubernetes.io/component: web-server
    app.kubernetes.io/part-of: angular-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: angular-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: angular-web
        app.kubernetes.io/version: 0.0.1
        app.kubernetes.io/component: web-server
        app.kubernetes.io/part-of: angular-web
    spec:
      containers:
        - name: angular-web
          image: angular-web:latest
          imagePullPolicy: Never
          livenessProbe:
            tcpSocket:
              port: 80
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-web
  labels:
    app.kubernetes.io/name: angular-web
    app.kubernetes.io/version: 0.0.1
    app.kubernetes.io/component: web-server
    app.kubernetes.io/part-of: angular-web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: angular-web
  ports:
    - name: http
      port: 80
