auth:
  createAdminUser: true
  adminUser: user
  adminPassword: password
service:
  type: ClusterIP
  port: 80
  httpsPort: 443
ingress:
  enabled: true
  hostname: "auth.latihan.jocki.me"
  ingressClassName: "nginx"
  path: /
  pathType: Prefix
  tls: true
  existingSecret: "tls-secret"
postgresql:
  postgresqlPassword: password
proxyAddressForwarding: true