apiVersion: v1
kind: Secret
metadata:
  name: app-jwt-secret
type: 'ENC[AES256_GCM,data:XtLoJ3tP,iv:U30O/xYpNg2OOzJg14SZ2aD0FLcVQQ1fEQtBOHYquB8=,tag:MnymvXIMnDJmKZ5IDfKblQ==,type:str]'
data:
  kongCredType: 'ENC[AES256_GCM,data:IxugDA==,iv:dem2vvEJbtzh8K/uTLfWuUlEK9VbzO3WqtRfxcWVriA=,tag:6KFJhyxFhankiqH9Ob5Kjw==,type:str]'
  key: 'ENC[AES256_GCM,data:S0tbwodytvTLQWLl2pUKiFmqD7YiZ93jMXlaCYwRJY1qOf+tgEZApxlruUvP0x/tSmX7j/Q62wc/1KGU3wfgato/tLA=,iv:P/TXPncg8m7O1FL8tOBZLvtaXFMLJHMEzk5RpvHh4yQ=,tag:/MRoYH0M5QCx6vXHYZ4N0Q==,type:str]'
  algorithm: 'ENC[AES256_GCM,data:pQ8pMYQYKFU=,iv:9YHh4NlRcA+olO+DO3qs/PO6zdbYw9MUIMheJduR8Zo=,tag:NcqrfuZ0kff0uLL03dx84g==,type:str]'
  rsa_public_key: 'ENC[AES256_GCM,data:RakA4k62F8ISZZNG25GLROcfOGJ+dFxVKUX2cORgURIYQjcw5SCASpA/YI22K/ZpJBgAfowAVnvyb0QH+b9QAttch5zzx4QEMRkP1VYnZHfVLOPJO2FYx7XtTZ9KQ5zREBFiF2SoeAJR6WdP+hC57x8ETQ5zHk3HT5iPPEIrrKcnoG+1dEhiXk42yH4cDW9iREcjjgfXuRC93u0ZnUMi/wsig+OLsi/ds9Ln6EdjWujkML1KRL8XB3Brngf62wwr2lOv8KZWGY48U1ei+4ozaXCUT8S8coLfRr1aF1W+hkg+u+42xgU1UptcqpWhJa3kE3PDQfhFMGCw4gCgHSxG9bKaQfN+pgJvNhS8tJQX06xe/Bhz71VgaQzTcigJCi8FdeURO6qJ4tB5FNY0CswJIqEh96Nw6FA8Oa1dwFy/D0C57XGtdo9xckdNnsSyl5sGqaIR0y7vD9DvJQmybPPq6FRc7KMv65ed+e/poHw3KC1r3BYEMmhMs9ZxUqObtC2fDcxml2vMFbG1UW8DwrwVRJETbYTDDRvdHI8DnQoA82nIkJ29d3pO/urH0M8ME6JMU95mI2tGy3K6TCx9chlRiCm8Aqc3HRNNTzFCBR9GVdVTjiUjdbTQbQ/a3rpBOtnKfAyZcFGexfLBWO7WkWqFBdYZAwX7Atmg99C9vJIIQWHp0LRL8XV/xXI2ZRQ5FnqFoFsX8bRoiGl0Wfndctz0eK2Y17K+TK+Yptx1odRdBF3AXbNuHLoIaD1kwcZBId3RGUPvLIYgJ3OlMwUVdiaKiFG+IsA=,iv:VrPqbqvrr8+BowNzvqiNEO/JurbN0FdxD8Vb+T120dE=,tag:FhhaEwm2eULgbyJquv4Ynw==,type:str]'
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2022-01-22T18:12:38Z'
  mac: 'ENC[AES256_GCM,data:vjHmefbWJSgLvJvu6B+F3+3YyjHOA6f/et26f218YfJIU/PiWM9H/dgD77nT0jh0NpE9U8wikzPEybuZmki9cu+GZMa4vYRir68FFiTjjMsceGEnf4rWtyoHOxeEWE8kFWTk9ed3HUjSXBEdrr1f6Q1dHei6nK9UPEVbG2bGoPk=,iv:r5Jqe8zOJOHb9PYWHpxzIPj6MKeW0cMbPGoWA2Y7Ck0=,tag:l+EqP2QgVPCxjVov+K/e5w==,type:str]'
  pgp:
  - created_at: '2022-01-22T18:12:38Z'
    enc: |
      -----BEGIN PGP MESSAGE-----

      hQIMA0v3SRnpVg8+AQ/9E4QvGSAey/whL2bQzEd/q8TF9qFY7KLyZxop1iUqabqo
      Xcs0/q428BYW7p90v3zSnczbmn837ttIDFwc/tSV0tcTiTnFqRRjIRGbySZdDnj8
      PamOOrIPZknuNPTIleejLFD1w9EGiioW3aprMsw1Wb9dMEqN5CepJZWouJnrj+Pe
      8+/b7ecIc89mFL8c0iqXebmBKV4dfYG7bBQHlBoAg9WH9j4U3mfqZPhd6D+t7UaF
      nMkmZYzrhIJF6N8IeksNeuK8npjWu2eFSnaVxSSe5zDXDWZ3Jstwq+Bse9CrKDyH
      XaZdXMrQ/M8V3ovFWkzbrclv+lZXeS+W/O+I0l25w855I6x1tvJRtR7dEBR0OO8s
      8cHuLK0Xyhf9gy9GSzcm7j/eBUaGoQ2zWO6bFkFJoAZRX0DmlgkO3N24WnS7EZ6E
      rVv4hatUUDpc/RitdXXz7iRRIxzA/MqH/ZV2nm3TM83xBIXC8WvW7IWML7UDBzGO
      1bMwD8HQy6EGsXtWcblBoNBy9hMVxgysE4JU0gx2fuMg5H4oWG1TOPgyhGTTM3cS
      wwJC8qPIAKeOrO6+Cz75IW9vR0UP/qQ2bLMx77tMOwMKYOt9H+p4xu3JWvSlezIv
      dlEnn4IjW5G9L9Xv5iIVpOyZqNuFCL7V0bnTmnYgddzhSQp/UyY2Gi7wR15Y/dHS
      XgGKxrz9BOdpA26ehJK59fp9V0D1GI8yh+J7BHFwwK/97tvdjbTfyDjlEmr5o97W
      xocr1fQO30VuhEm6QHe90T4rcsZNX/BDSAM6BnG+WRxuAfsfMgQINbTVlJy9FGI=
      =kcxP
      -----END PGP MESSAGE-----
    fp: FFA6D9C42D878F5C
  unencrypted_regex: ^(kind|apiVersion|group|metadata)$
  version: 3.7.1
