apiVersion: v1
kind: Secret
metadata:
  name: app-jwt-secret
  labels:
    env: staging
type: 'ENC[AES256_GCM,data:Oht/DnwJ,iv:ZSqJOkm2keeNXMWjOWOsU4Es5Djw4yy65fn2m2OqkpI=,tag:7GoF3F60dldGhYfqJ1gaZQ==,type:str]'
data:
  kongCredType: 'ENC[AES256_GCM,data:6RyTQw==,iv:nynbxsD//vMBCD+w5t3zamRWe14nhbDJmWm5qG2CQGk=,tag:wIYEbfXTiEb4GSal+dj5ow==,type:str]'
  key: 'ENC[AES256_GCM,data:+xr04YsOy0w7YzKQroeaowsiUylLUoIRZVZPHptOJaAo/37tvWfF99VM4P3ZgaDDuxH5TAMeCbKlfNFk+uk3pMvmazY=,iv:WpS9ztkV2P0zfSYixTuyfOKVbNZy/IOJb/5OrPQk+88=,tag:33QW7oJewkh0/AsoSZTDOg==,type:str]'
  algorithm: 'ENC[AES256_GCM,data:pubWrsVvaxY=,iv:WRLs/+AIsJsBSTSh5yV1TcD5feSm+sWbWfjP9zaWSEQ=,tag:ldADSXL+X0vI2M/EtkkvcA==,type:str]'
  rsa_public_key: 'ENC[AES256_GCM,data:hhATjRp5bHW8IWvjtoYS4VRjWfNoBfxs4PStbA6EtfO1qIy6b+FzNASIfe3+qwLTltlYHb1i5NcAqbV4NcQBwTHuTNxu/2Q9GOjcVKlfctGXxhIgQAlN7ntgOlGGzbxSQerTcnTMYyhy2Xp7U+9jAhY/jfNYYRicIkmdPUJ9n8yhA+RCX/3aZ4aC/tbn2Xn/K89UyqUMOfWAAOUo6EMIMQvbl8E36DQiIBkSl7dFLLK+9gY39Ywky7MZoiIJNqEdGMBjG3b/AJ4FvoelujNYEfCbmEA2P5OR9FXbmJ3isHllHk6Th+bTz8bdirIzZzFILHqRSJM8UOhLTkagYA8wvlWc+5vucJRbc0zaU+/z1bl6V2OzAY5nHeYGuFFnfMNrUZKDUrvj0IlWWrTK2kgHuoXgCsInF7XelyXJ0jBDbj2j5uPg0xrDEYiJrO6J2meKx5pVYP+bSR6/i3MbNsHg5s1lmFh5AJC9d7sAbaZ2g2DEXpvuTdetQKnrRjTuZ1/y+xz92KjDr786/8xDKyfrk6n/dg0POjuZPNhbp3DS86Ud/gaBuvS2acrYuuauz3c3poVHRi1lbdgqJMzjpjUbjytgpMoffFD1LhgqV8Z4oQfgKNPpGiq3fu+6GpZb2H+zUzW9KCRA5WYtpijGqINhO3mqlfJw/mRCJr2isUaVFAptnL/e8spwOTB4tbFF+SW1iSIxbOTa7YJkDoUCmAimDQIfrcM08yCT8hvzqCAyfpi34ZjjjAQgZJmLfZY6/sRPwapAX5Nnxr6pI68EMKyXp4Ds2/4=,iv:i8g3Arv1l1KOp1RQNDf8dxGjevGMa0y0z969ljyBDEs=,tag:jyYr2hjoVPwg2j8/XApFnw==,type:str]'
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2022-02-13T08:14:54Z'
  mac: 'ENC[AES256_GCM,data:LrjvQaO1+/F5ZqJVyJhFbBYZiq1zp/ylZ+360pS83+I6wvoqS5By6YtbT4/cKnK3eG06nvdp0DzPsHEKQBTYRd+U+8E1fM/fBCjn+CRUAKpYDr5pRYnQmcNblHUz330LACFwUioYjYrCOvUUAoGADvVMMChk9Wup8+y15iyLKX0=,iv:rOx6pd1gvvZ8fPH8zWQQgBkfl0zpzSwU7R5Mjepx28o=,tag:v2Hn35Ao42vZCNUGrxwSZg==,type:str]'
  pgp:
  - created_at: '2022-02-13T08:14:54Z'
    enc: |
      -----BEGIN PGP MESSAGE-----

      hQIMA0v3SRnpVg8+AQ/9FpKnAC3UCEiFtNOWT1iUoq8ElFTpjfMSedFdMqG7ahbm
      TYzd6xngksVM2py8J+IHVc59MuB0D8UD6SL2rN31u9SXLsBiLBi0JpxhDhJlnXmt
      lVhHk0sVRq1RuO1T5UBSTcndkToXnpOrgpUFbnnvlvAF7dgO5lzWag8RFg2zkfww
      xUAq7mzmhIiG7E4rV67rfA3dJkK35WBqKrcM/lrYc7b7P0JHs7Jap5bB0oYjVUJK
      Hg4CuOe8FE/z4fthpAkigeALBAdr3kzExsMYH2AfNbLo8YMyyETuG79SHsSHoI9f
      ksZIAiyAsQPU04eSZO/hACQJbvm9A4DZFwkj3ibGLNp99s68zDDAZ4txKuriRGyj
      n8+Fz3eumsJwpEL5lwj4A84K3ykqkRd6Fxw+Jdcmx910ViE3Y+Oki+HOzIkQbDYS
      4iRFijXrgbj/Y4TL+WqO7Gu/7mn/sfaAmZXzs9E69HIAmDrZTM0O76Rya9A6XiyG
      vE9FOn/ml79vsMzDKPn8etjggUozQtLV64Qn6RLqUvQYjkQ84tEptpmbHI4Pugbv
      zrHqGCjhRMzPt8KuN3ZTyJrX4xfxaFP7Pb6MfZrXus7Vj8FToJxKsHIXGkdj07gj
      ebF0+xEifPgTH6dAcNIbslxPSyoGnXMAiDF8Q0fqX52VGsc3g/ttjl37X6hAh9LS
      XgFUXYekBTISeci72cUftoaXTMxYardHR8mffSnw6oJbX5V+I6NV/sA9WZnNke5E
      XVhEod57xh9oUOydoA7D1SwmyMZ+eVBIgqfTK+Yw2heGVmIRw5+4jfgDtxd3rFk=
      =DP+z
      -----END PGP MESSAGE-----
    fp: FFA6D9C42D878F5C
  unencrypted_regex: ^(kind|apiVersion|group|metadata)$
  version: 3.7.1
