apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: refresh-jwt-secret
  annotations:
    config.kubernetes.io/local-config: 'true'
params:
  key: 'https://auth-default.latihan.jocki.me/auth/realms/latihan' # kpt-set: https://auth-${tenant}.${domain}/auth/realms/latihan
source: |
  load('http.star', 'http')
  load('encoding/base64.star', 'base64')
  key = ctx.resource_list['functionConfig']['params']['key']
  for r in ctx.resource_list['items']:
    if r['kind'] == 'Secret' and r['metadata']['name'] == 'app-jwt-secret':
      r['data']['kongCredType'] = base64.encode('jwt')
      r['data']['key'] = base64.encode(key)
      r['data']['algorithm'] = base64.encode('RS256')
      realm_info = http.get(key).json()
      public_key = realm_info['public_key']
      if not public_key.startswith('-----BEGIN PUBLIC KEY-----'):
        public_key = '-----BEGIN PUBLIC KEY-----\n{}\n-----END PUBLIC KEY-----'.format(public_key)
      r['data']['rsa_public_key'] = base64.encode(public_key)
