name: stock-item-service
on:
  push:
    branches:
      - main
    paths:
      - stock-item-service/**
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: jockihendry/latihan-k8s-stock-item-service

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: temurin
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=edge,branch=main
      - name: Build and push
        working-directory: ./stock-item-service
        run: |
          ./gradlew test bootBuildImage \
          -PregistryUsername=${{ github.actor }} -PregistryPassword=${{ secrets.GITHUB_TOKEN }} -PimageTags="${{ join(fromJSON(steps.meta.outputs.json).tags) }}" \
          --imageName=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
          --publishImage
